name: Build and Deploy Spring Boot Lambda

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch

jobs:
  build:
    name: Build Spring Boot JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Zip the JAR for Lambda
        run: |
          mkdir package
          cp target/*.jar package/
          cd package
          zip -r springboot-lambda.zip *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: package/springboot-lambda.zip

  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    needs: build  # Waits for build job to complete

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-package
          path: package

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1  # Change if needed

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name springboot-lambda \
            --zip-file fileb://package/springboot-lambda.zip
