name: Build and Deploy Spring Boot Lambda

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch

jobs:
  build:
    name: Build Spring Boot JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Zip the JAR for Lambda
        run: |
          mkdir package
          cp target/*.jar package/
          cd package
          zip -r springboot-lambda.zip *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: package/springboot-lambda.zip

  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    needs: build  # Waits for build job to complete

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-package
          path: package

      - name: Update AWS CLI (If Already Installed)
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version  # Verify installation

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change region if needed

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}" \
            --zip-file fileb://package/springboot-lambda.zip

